version: '3.8'

services:
  grpc-server:
    build: 
      context: .
      dockerfile: Dockerfile
    command: python include/grpc_server.py
    volumes:
      - ./images:/app/images
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "50051:50051"
    restart: unless-stopped
    environment:
      - CUDA_VISIBLE_DEVICES=0

  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    volumes:
      - ./images:/app/images
    ports:
      - "8501:8501"
    depends_on:
      - grpc-server
    restart: unless-stopped
    environment:
      - GRPC_SERVER_ADDRESS=grpc-server